create TABLE IF NOT EXISTS hits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server      VARCHAR(75) NOT NULL,
    uri         VARCHAR(255)  NOT NULL,
    ip          VARCHAR(130) NOT NULL,
    time        TIMESTAMP NOT NULL
);